#!/usr/bin/env python3
"""Step 2b — MID-FLOW re-conditioning: the isoconfigurational move translated to root flows.
EXPLORATORY AND UNSEALED. All rules below PINNED 2026-08-13 before any per-bin curve at k=2
conditioning was seen.

DESIGN: identical to Step 2 (step2_env_decomposition.py, pinned b28c082) with ONE change — the
conditioning configuration moves from k = 0 (the seed) to k = 2 (two steps into the flow).
Environment of root j at step k > 2: ancestry cone in the k=2 configuration,
E_j(k) = (x2_{j+k-2} - x2_j)/(k-2), the exact mirror of Step 2's rule with the reference
configuration shifted. Quintile bins per (replicate, k); per-root two-gap ratio on the v1.5.1
corrected unfolding; sealed ladder machinery per bin; K_GRID = {4, 6, 8, 12, 16, 24, 32, 64}
(k > 2 only; 6, 12, 24 added for resolution in the transition window — pinned here).

INTERPRETATION LADDER (pre-committed, same thresholds as Step 2):
- SUPPORTED (F2 in >= 4/5 bins AND tau_b strictly monotone across quintiles): conditioning on
  the INSTANTANEOUS configuration decomposes the stretch that seed-conditioning could not —
  the rate heterogeneity is carried by the evolving configuration, i.e. GENERATED BY THE FLOW:
  the dynamical-heterogeneity scenario is supported and the Step 2 vs Step 2b contrast is the
  isoconfigurational separation performed.
- NOT_SUPPORTED (F3 with beta < 0.9 in >= 3/5 bins): instantaneous-environment conditioning
  ALSO fails to decompose — the stretch is not captured by local gap environment at any single
  time; intrinsic local nonexponentiality gains ground (with the stated caveat that the
  environment variable may be too crude — that caveat is pinned NOW, not invented after).
- MIXED otherwise: filed as MIXED, full stop.
Consistency witness (reported, not adjudicating): population-weighted per-bin sum vs aggregate.
"""
import json, time
import numpy as np
from track0_harness import diff_step, bulk_idx
from free_conv import F_empirical
from track0_iid_scaling import reference_cdf
from science_rate_question import fit_ladder
from step2_env_decomposition import per_root_ratios

N = 4096
K_COND = 2
K_GRID = [4, 6, 8, 12, 16, 24, 32, 64]
R = 16
NBINS = 5
FIT_WINDOW_MIN = 1e-3
MASTER_SEED = 20260811


def run():
    t0 = time.time()
    children = np.random.SeedSequence(MASTER_SEED).spawn(96)
    acc = {k: [[] for _ in range(NBINS)] for k in K_GRID}
    agg = {k: [] for k in K_GRID}
    for i in range(R):
        seed = np.sort(np.random.default_rng(children[32 + i]).uniform(-1.0, 1.0, N))
        F_seed = F_empirical(seed)
        r = seed.copy()
        x2 = None
        for k in range(1, K_GRID[-1] + 1):
            r = diff_step(r)
            if k == K_COND:
                x2 = r.copy()                       # the conditioning configuration
            if k not in K_GRID:
                continue
            m = N - k
            F_at, _ = reference_cdf(F_seed, r, k / N, m)
            u = F_at * m
            bi = bulk_idx(m)
            lo, hi = bi.start, bi.stop
            ratios = per_root_ratios(u)
            j_idx = np.arange(max(lo, 1), min(hi, m - 1))
            rj = ratios[j_idx - 1]
            cone = k - K_COND
            E = (x2[j_idx + cone] - x2[j_idx]) / cone
            edges = np.quantile(E, np.linspace(0, 1, NBINS + 1))
            edges[0] -= 1e-12; edges[-1] += 1e-12
            which = np.digitize(E, edges) - 1
            for b in range(NBINS):
                acc[k][b].append(1.0 - float(np.mean(rj[which == b])))
            agg[k].append(1.0 - float(np.mean(rj)))
        print(f"  rep {i} done", flush=True)

    out = {"step": "Step 2b isoconfigurational (exploratory, unsealed)", "K_COND": K_COND,
           "per_bin": {}, "aggregate": {}, "fits": {}, "ladder_outcome": None}
    for k in K_GRID:
        out["aggregate"][str(k)] = {"mean": float(np.mean(agg[k])),
                                    "sigma_mean": float(np.std(agg[k], ddof=1) / np.sqrt(R))}
        out["per_bin"][str(k)] = [{"mean": float(np.mean(acc[k][b])),
                                   "sigma_mean": float(np.std(acc[k][b], ddof=1) / np.sqrt(R))}
                                  for b in range(NBINS)]
    sel_forms, taus, betas = [], [], []
    for b in range(NBINS):
        ks = [k for k in K_GRID if out["per_bin"][str(k)][b]["mean"] > FIT_WINDOW_MIN]
        means = np.array([out["per_bin"][str(k)][b]["mean"] for k in ks])
        sm = np.array([out["per_bin"][str(k)][b]["sigma_mean"] for k in ks])
        sel, fits = fit_ladder(np.array(ks, dtype=float), means, sm)
        out["fits"][f"bin{b}"] = {"fit_window_k": ks, "selected": sel, "ladder": fits}
        sel_forms.append(sel)
        p = fits[sel].get("params")
        taus.append(p[1] if sel in ("F2", "F3") and p else None)
        betas.append(p[2] if sel == "F3" and p else None)
    n_f2 = sum(1 for f in sel_forms if f == "F2")
    n_f3_stretch = sum(1 for f, be in zip(sel_forms, betas) if f == "F3" and be is not None and be < 0.9)
    tau_ok = all(t is not None for t in taus) and \
        (all(taus[b] < taus[b + 1] for b in range(NBINS - 1)) or
         all(taus[b] > taus[b + 1] for b in range(NBINS - 1)))
    out["ladder_outcome"] = ("SUPPORTED" if n_f2 >= 4 and tau_ok else
                             "NOT_SUPPORTED" if n_f3_stretch >= 3 else "MIXED")
    out["selected_forms"] = sel_forms
    out["taus"] = taus
    out["betas"] = betas
    out["runtime_s"] = round(time.time() - t0, 1)
    with open("derivflow/step2b_isoconfig.json", "w") as f:
        json.dump(out, f, indent=1)
    print(f"\nLADDER OUTCOME: {out['ladder_outcome']}")
    print("forms:", sel_forms)
    print("taus:", [None if t is None else round(t, 3) for t in taus])
    print("betas:", [None if b is None else round(b, 3) for b in betas])
    print(f"runtime {out['runtime_s']}s")


if __name__ == "__main__":
    run()
