"""Generate a one-page morning summary by pooling all overnight JSON results.

Reads all *_results.json files in data/ and produces a Markdown summary
that the user can scan in 30 seconds.

Output: MORNING_SUMMARY.md
"""
import os, json, glob

THIS_DIR = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(THIS_DIR, "data")
OUT = os.path.join(THIS_DIR, "MORNING_SUMMARY.md")


def load(name):
    p = os.path.join(DATA, name)
    if not os.path.exists(p): return None
    try:
        with open(p) as f: return json.load(f)
    except Exception:
        return None


lines = []
def w(s=''): lines.append(s)


w("# Morning summary — overnight pipeline results")
w()
w("Auto-generated by `run_morning_summary.py`. Re-run any time to refresh.")
w()


# ─── Calibration anchors ──────────────────────────────────────────────────────
w("## Calibration anchors (from RESULTS.md §6.4)")
w()
w("| signal | best | KS_min | n |")
w("|---|---|---|---|")
w("| GUE eigenvalues | GUE | 0.022 | 13,971 |")
w("| GOE eigenvalues | GOE | 0.021 | 13,965 |")
w("| Poisson uniform | Poisson | 0.018 | 17,628 |")
w("| ζ first 100k zeros (Odlyzko zeros1) | GUE | 0.015 | 1,845,065 |")
w()


# ─── ζ height convergence ─────────────────────────────────────────────────────
zhc = load("zeta_height_convergence.json")
if zhc:
    w("## ζ-zero height-dependent GUE convergence")
    w()
    bins = zhc.get('bins', [])
    if bins:
        w(f"21 bins of 100k zeros each, heights 14 → 1,132,490.  "
          f"Bin 1 KS_GUE = {bins[0]['ks_u']:.4f}; bin {len(bins)} KS_GUE = "
          f"{bins[-1]['ks_u']:.4f}.  Monotone decrease confirms asymptotic GUE.")
        w()
        w("| bin | heights | KS_GUE | gap | best |")
        w("|---|---|---|---|---|")
        for b in [bins[0], bins[len(bins)//2], bins[-1]]:
            w(f"| {b['idx_lo']:,}-{b['idx_hi']:,} | {b['t_lo']:.0f}-{b['t_hi']:.0f} | "
              f"{b['ks_u']:.4f} | {b['gap']:+.3f} | {b['best']} |")
        w()


# ─── LMFDB elliptic curves bulk ───────────────────────────────────────────────
lmfdb = load("lmfdb_results.json")
if lmfdb:
    w("## LMFDB elliptic curve L-functions, conductor ≤ 99")
    w()
    w(f"{lmfdb.get('n_curves', '?')} isogeny class reps, ~280 zeros/curve at h≤200.")
    w()
    w("| group | best | KS_min | gap | n |")
    w("|---|---|---|---|---|")
    for k, v in lmfdb.get('aggregates', {}).items():
        if not isinstance(v, dict) or 'best' not in v: continue
        ks_min = min(v.get('ks_p', 1), v.get('ks_o', 1), v.get('ks_u', 1))
        w(f"| {k} | {v['best']} | {ks_min:.3f} | {v.get('gap', 0):+.3f} | {v.get('n', '?')} |")
    w()

# Edge γ_1 test
le = load("lmfdb_edge_results.json")
if le and 'gamma1_normalised' in le:
    g = le['gamma1_normalised']
    w("**Katz-Sarnak edge test (γ_1 normalised by log(N)/(2π))**:")
    w(f"  - SO_even (root_number = +1): mean = {g['plus_one']['mean']:.3f} ± {g['plus_one']['std']:.3f}")
    w(f"  - SO_odd  (root_number = −1): mean = {g['minus_one']['mean']:.3f} ± {g['minus_one']['std']:.3f}")
    w(f"  - Two-sample KS: **{g['ks_two_sample']:.3f}**, p ≈ **{g['p_value']:.4f}**")
    w()


# ─── Dirichlet ────────────────────────────────────────────────────────────────
dr = load("dirichlet_results.json")
if dr:
    w("## Dirichlet L-functions")
    w()
    n_ch = len(dr.get('per_character', []))
    qr = dr.get('config', {}).get('q_range', [])
    q_lo = qr[0] if qr else '?'
    q_hi = qr[-1] if qr else '?'
    w(f"{n_ch} primitive non-trivial characters, q ∈ {q_lo}..{q_hi}.")
    w()
    w("| group | best | KS_min | gap | n |")
    w("|---|---|---|---|---|")
    for k, v in dr.get('aggregates', {}).items():
        if not isinstance(v, dict) or 'best' not in v: continue
        ks_min = min(v.get('ks_p', 1), v.get('ks_o', 1), v.get('ks_u', 1))
        w(f"| {k} | {v['best']} | {ks_min:.3f} | {v.get('gap', 0):+.3f} | {v.get('n', '?')} |")
    w()

de = load("dirichlet_edge_results.json")
if de:
    w("**Dirichlet edge γ_1 (normalised by log(q)/(2π))**:")
    g = de.get('gamma1_normalised', {})
    if g:
        w(f"  - real (Sp predicted): mean = {g['real']['mean']:.3f} ± {g['real']['std']:.3f}")
        w(f"  - complex (U predicted): mean = {g['complex']['mean']:.3f} ± {g['complex']['std']:.3f}")
        w(f"  - Two-sample KS: **{g['ks_two']:.3f}**, p ≈ **{g['p']:.4f}**")
    w()


# ─── Mertens / Liouville ──────────────────────────────────────────────────────
ml = load("mertens_liouville_results.json")
if ml:
    w("## Mertens M(x) and Liouville L(x) sign-change positions")
    w()
    w(f"Sieved up to x = 10⁷.  Mertens has "
      f"{ml.get('mertens', {}).get('n_sign_changes', '?')} sign-changes; "
      f"Liouville has {ml.get('liouville', {}).get('n_sign_changes', '?')} "
      f"(Pólya conjecture territory — L(x) ≤ 0 for almost all x ≤ 906M).")
    w()
    m_an = ml.get('mertens', {}).get('analytical_nns', {})
    if m_an and m_an.get('best') != 'insufficient':
        w(f"  - Mertens NNS: best = **{m_an['best']}**, KS_P = {m_an.get('ks_p', '?'):.3f}, mass<0.3 = {m_an.get('mass03', '?'):.3f}")
    w()


# ─── Earthquakes ──────────────────────────────────────────────────────────────
eq = load("earthquake_results.json")
if eq:
    w("## USGS earthquakes M ≥ 4.5, 2020-2024")
    w()
    w(f"{eq.get('n_events', '?'):,} events over {eq.get('span_years', '?'):.2f} years.")
    w()
    g = eq.get('global_nns', {})
    w(f"**Global NNS**: best = **{g.get('best', '?')}**, KS_P = {g.get('ks_p', '?'):.3f}, "
      f"KS_GUE = {g.get('ks_u', '?'):.3f}, mass<0.3 = {g.get('mass03', '?'):.3f}")
    w()


# ─── Σ²(L) cross-family ───────────────────────────────────────────────────────
so = load("second_order_results.json")
if so:
    w("## Σ²(L) cross-family")
    w()
    w("| family | Σ²(L=2) | Σ²(L=10) | Σ²(L=20) | regime |")
    w("|---|---|---|---|---|")
    sd = so.get('sigma2_by_family', {})
    for name, d in sd.items():
        L = d['L']; s2 = d['sigma2']
        try:
            s2_2 = s2[next(i for i, l in enumerate(L) if l > 1.9)]
            s2_10 = s2[next(i for i, l in enumerate(L) if l > 9.9)]
            s2_20 = s2[next(i for i, l in enumerate(L) if l > 19)]
            s2_2 = f"{s2_2:.2f}"
            s2_10 = f"{s2_10:.2f}"
            s2_20 = f"{s2_20:.2f}"
        except Exception:
            s2_2 = s2_10 = s2_20 = '?'
        regime = ('clustering (super-Poisson)' if 'arthquake' in name
                  else 'log-growth (GUE-class)')
        w(f"| {name} | {s2_2} | {s2_10} | {s2_20} | {regime} |")
    w("| (Poisson reference) | 2.00 | 10.00 | 20.00 | linear |")
    w("| (GUE reference) | 0.56 | 0.90 | 1.05 | log |")
    w()


# ─── Pair correlation ────────────────────────────────────────────────────────
pc = load("pair_correlation_results.json")
if pc:
    w("## Pair correlation R₂(r)")
    w()
    w("R₂(r→0) = 0 is the GUE level-repulsion signature.  Earthquakes show the opposite (R₂ > 1 = clustering).")
    w()
    w("| family | R₂(0.1) | R₂(0.3) | R₂(1.0) |")
    w("|---|---|---|---|")
    for name, d in pc.items():
        if not isinstance(d, dict) or 'r' not in d: continue
        r = d['r']; R2 = d['R2']
        try:
            r1 = R2[next(i for i, x in enumerate(r) if x > 0.09)]
            r2 = R2[next(i for i, x in enumerate(r) if x > 0.29)]
            r3 = R2[next(i for i, x in enumerate(r) if x > 0.99)]
            w(f"| {name} | {r1:.3f} | {r2:.3f} | {r3:.3f} |")
        except StopIteration:
            continue
    w("| GUE prediction | 0.033 | 0.270 | 1.000 |")
    w("| Poisson | 1.000 | 1.000 | 1.000 |")
    w()


# ─── EEG ──────────────────────────────────────────────────────────────────────
eeg = load("eeg_results.json")
if eeg:
    w("## EEG θ-band zero-crossings (PhysioNet EEGMMIDB, 3 subjects)")
    w()
    w("Reminder (from RESULTS.md §7.ter.2): GUE-best at KS≈0.18 is **NOT** a clean")
    w("Wigner GUE classification — KS is 8× the calibrator threshold.  These are")
    w("quasi-periodic biological signals, and the metric reports 'most s²-suppressed")
    w("among the three Wigner forms', not GUE-class dynamics.")
    w()
    a = eeg.get('aggregates', {}).get('by_condition', {})
    if a:
        w("| condition | KS_GUE | mass<0.3 |")
        w("|---|---|---|")
        for cond, v in a.items():
            if isinstance(v, dict) and 'ks_u' in v:
                w(f"| {cond} | {v['ks_u']:.3f} | {v.get('mass03', '?'):.3f} |")
    w()


# ─── Files inventory ──────────────────────────────────────────────────────────
w("## Files written this session")
w()
w("```")
for fn in sorted(os.listdir(DATA)):
    if fn.endswith('.json'):
        path = os.path.join(DATA, fn)
        size = os.path.getsize(path)
        w(f"  data/{fn:<40s} ({size:,} bytes)")
w("")
plot_dir = os.path.join(THIS_DIR, "plots")
for fn in sorted(os.listdir(plot_dir)):
    if fn.endswith('.png'):
        size = os.path.getsize(os.path.join(plot_dir, fn))
        w(f"  plots/{fn:<40s} ({size:,} bytes)")
w("```")
w()


# ─── Pipeline state ──────────────────────────────────────────────────────────
w("## Pipeline state")
w()
import subprocess
try:
    ps = subprocess.run(['ps', '-eo', 'pid,etime,cmd'], capture_output=True, text=True, timeout=5).stdout
    relevant = [l for l in ps.split('\n')
                if any(s in l for s in ['run_lmfdb', 'run_dirichlet', 'run_mertens'])
                and 'grep' not in l]
    if relevant:
        w("Background processes running:")
        w("```")
        for line in relevant: w(f"  {line.strip()}")
        w("```")
    else:
        w("All overnight processes complete.")
except Exception:
    pass


with open(OUT, 'w') as f:
    f.write('\n'.join(lines) + '\n')
print(f"Wrote {OUT}")
