"""
transition_calibrators_blended.py — Phase 20.5 Tier 1.A.

Constructive (blended) transition calibrators: synthetic event sequences
generated by interpolating between two known universality classes via
controlled blending functions.  Six transition shapes × eight class pairs
plus stationary controls.

The framework lacks calibrated transition-shape recognition; without
controlled-construction calibrators, per-sub-window trajectories through
classification space (Phase 20 BGP cascades, Phase 21 GRB transitions)
can be observed but not characterised.  These calibrators provide
ground-truth substrates against which the trajectory diagnostic in
`transition_diagnostic.py` is validated.

Eight class pairs (origin → destination, kept asymmetric — direction
matters for the diagnostic):

  GUE      → Poisson    | Wigner_GUE_to_Poisson
  Poisson  → GUE        | Poisson_to_Wigner_GUE
  GUE      → TL         | Wigner_GUE_to_periodic
  TL       → GUE        | periodic_to_Wigner_GUE
  Poisson  → TL         | Poisson_to_periodic
  TL       → Poisson    | periodic_to_Poisson
  GUE      → mixed      | Wigner_GUE_to_mixed
  mixed    → GUE        | mixed_to_Wigner_GUE

Six transition shapes:

  - sharp_step           — instantaneous switch at t_transition
  - linear_ramp          — linear interpolation over [t_start, t_end]
  - sigmoidal            — logistic interpolation, width w, mid t_mid
  - exponential_approach — characteristic time τ
  - damped_oscillatory   — damped sinusoid converging to destination
  - metastable_middle    — A → C → B with C held briefly

The blending API: at each event index, sample either origin or
destination according to a time-varying weight w(t) ∈ [0, 1].  The
event SEQUENCES from each class are pre-generated; the blended output
interleaves events according to the weight schedule.
"""
from __future__ import annotations

import os, sys
from typing import Callable, Optional

import numpy as np

THIS_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, THIS_DIR)

from signal_gen import (
    make_beta_ensemble_eigenvalues,
    make_uniform_jitter,
)


# ─── Stationary class generators ───────────────────────────────────────────


def gen_poisson(n_points: int, seed: int = 0) -> np.ndarray:
    rng = np.random.default_rng(seed)
    return np.cumsum(rng.exponential(1.0, size=n_points))


def gen_wigner_gue(n_points: int, seed: int = 0) -> np.ndarray:
    return make_beta_ensemble_eigenvalues(n_points, beta=2, seed=seed)


def gen_periodic(n_points: int, seed: int = 0, period: float = 7.0,
                  jitter: float = 0.05) -> np.ndarray:
    rng = np.random.default_rng(seed)
    t = np.arange(1, n_points + 1, dtype=np.float64) * period \
        + jitter * rng.standard_normal(n_points)
    return np.sort(t)


def gen_mixed(n_points: int, seed: int = 0,
              periods: tuple = (7.0, 12.0),
              weights: tuple = (0.4, 0.4),
              jitter: float = 0.05) -> np.ndarray:
    rng = np.random.default_rng(seed)
    streams = []
    for p, w in zip(periods, weights):
        n_p = int(n_points * w)
        t = np.arange(1, n_p + 1, dtype=np.float64) * p \
            + jitter * rng.standard_normal(n_p)
        streams.append(t)
    bg = np.cumsum(rng.exponential(periods[0], size=int(n_points * 0.3)))
    streams.append(bg)
    out = np.sort(np.concatenate(streams))
    return out[:n_points]


CLASS_GENERATORS = {
    'Poisson':    gen_poisson,
    'GUE':        gen_wigner_gue,
    'TL':         gen_periodic,
    'periodic':   gen_periodic,
    'mixed':      gen_mixed,
}


# ─── Shape weight schedules ────────────────────────────────────────────────


def shape_sharp_step(n: int, t_transition: float = 0.5) -> np.ndarray:
    """Weight schedule: 0 before t_transition (in [0, 1] fraction of n),
    1 after.  Returns array of length n with values in {0, 1}."""
    w = np.zeros(n)
    idx = int(t_transition * n)
    w[idx:] = 1.0
    return w


def shape_linear_ramp(n: int,
                       t_start: float = 0.3,
                       t_end: float = 0.7) -> np.ndarray:
    w = np.zeros(n)
    i_start = int(t_start * n)
    i_end = int(t_end * n)
    w[:i_start] = 0.0
    w[i_end:] = 1.0
    if i_end > i_start:
        w[i_start:i_end] = np.linspace(0.0, 1.0, i_end - i_start)
    return w


def shape_sigmoidal(n: int,
                     t_mid: float = 0.5,
                     width: float = 0.1) -> np.ndarray:
    """Logistic w(t) = 1 / (1 + exp(-(t - t_mid) / (width / 4)))."""
    t = np.linspace(0.0, 1.0, n)
    return 1.0 / (1.0 + np.exp(-(t - t_mid) / max(width / 4.0, 1e-6)))


def shape_exponential_approach(n: int,
                                tau: float = 0.2,
                                t_start: float = 0.3) -> np.ndarray:
    """w(t) = 1 - exp(-(t - t_start) / τ) for t ≥ t_start, else 0."""
    t = np.linspace(0.0, 1.0, n)
    w = np.zeros(n)
    mask = t >= t_start
    w[mask] = 1.0 - np.exp(-(t[mask] - t_start) / max(tau, 1e-6))
    return w


def shape_damped_oscillatory(n: int,
                              tau: float = 0.3,
                              omega: float = 4.0 * np.pi,
                              t_start: float = 0.2) -> np.ndarray:
    """Underdamped approach to 1: w(t) = 1 - exp(-(t-t_start)/τ) ·
    cos(ω(t-t_start))."""
    t = np.linspace(0.0, 1.0, n)
    w = np.zeros(n)
    mask = t >= t_start
    dt = t[mask] - t_start
    w[mask] = 1.0 - np.exp(-dt / max(tau, 1e-6)) * np.cos(omega * dt)
    return np.clip(w, 0.0, 1.0)


def shape_metastable_middle(n: int,
                              t_in: float = 0.25,
                              t_mid_start: float = 0.4,
                              t_mid_end: float = 0.6,
                              t_out: float = 0.75) -> np.ndarray:
    """Two-step weight: 0 → 0.5 (metastable middle) → 1.

    Actually returns a 2-D weight schedule (n, 3): w_origin, w_middle,
    w_destination — each row sums to 1.0.  This requires a separate
    blender path for three-state mixing.
    """
    w = np.zeros((n, 3))
    # Origin only
    i_in = int(t_in * n)
    w[:i_in, 0] = 1.0
    # Origin → middle ramp
    i_mid_start = int(t_mid_start * n)
    if i_mid_start > i_in:
        ramp = np.linspace(0.0, 1.0, i_mid_start - i_in)
        w[i_in:i_mid_start, 0] = 1.0 - ramp
        w[i_in:i_mid_start, 1] = ramp
    # Middle held
    i_mid_end = int(t_mid_end * n)
    w[i_mid_start:i_mid_end, 1] = 1.0
    # Middle → destination ramp
    i_out = int(t_out * n)
    if i_out > i_mid_end:
        ramp = np.linspace(0.0, 1.0, i_out - i_mid_end)
        w[i_mid_end:i_out, 1] = 1.0 - ramp
        w[i_mid_end:i_out, 2] = ramp
    # Destination only
    w[i_out:, 2] = 1.0
    return w


SHAPES_TWO_STATE = {
    'sharp_step':           shape_sharp_step,
    'linear_ramp':          shape_linear_ramp,
    'sigmoidal':            shape_sigmoidal,
    'exponential_approach': shape_exponential_approach,
    'damped_oscillatory':   shape_damped_oscillatory,
}


SHAPES_THREE_STATE = {
    'metastable_middle': shape_metastable_middle,
}


# ─── Blender ───────────────────────────────────────────────────────────────


def _blend_two_class(origin_events: np.ndarray,
                      destination_events: np.ndarray,
                      weights: np.ndarray,
                      rng: np.random.Generator,
                      ) -> np.ndarray:
    """Blend two pre-generated unit-mean class sequences according to
    a per-index weight schedule.

    For each output index i ∈ [0, n), draw from `destination_events`
    with probability `weights[i]`, else from `origin_events`.  We
    pre-shuffle both sequences and pop in order to avoid re-using the
    same event positions across draws.

    Output is sorted with unit mean spacing.
    """
    n = weights.size
    # Pre-shuffle indices
    o_idx = rng.permutation(origin_events.size)
    d_idx = rng.permutation(destination_events.size)
    o_pos = 0
    d_pos = 0
    out = []
    for i in range(n):
        if rng.uniform() < weights[i]:
            # Take from destination
            if d_pos < d_idx.size:
                out.append(float(destination_events[d_idx[d_pos]]))
                d_pos += 1
            elif o_pos < o_idx.size:
                out.append(float(origin_events[o_idx[o_pos]]))
                o_pos += 1
        else:
            if o_pos < o_idx.size:
                out.append(float(origin_events[o_idx[o_pos]]))
                o_pos += 1
            elif d_pos < d_idx.size:
                out.append(float(destination_events[d_idx[d_pos]]))
                d_pos += 1
    out = np.sort(np.asarray(out, dtype=np.float64))
    sp = np.diff(out)
    sp = sp[sp > 0]
    if sp.size and sp.mean() > 0:
        out = np.cumsum(np.concatenate([[0.0], sp / sp.mean()]))
    return out


def _blend_three_class(origin_events: np.ndarray,
                        middle_events: np.ndarray,
                        destination_events: np.ndarray,
                        weights: np.ndarray,
                        rng: np.random.Generator,
                        ) -> np.ndarray:
    """Three-state blender for metastable_middle shape.  weights is
    shape (n, 3) with rows summing to 1.0."""
    n = weights.shape[0]
    o_idx = rng.permutation(origin_events.size)
    m_idx = rng.permutation(middle_events.size)
    d_idx = rng.permutation(destination_events.size)
    o_pos = m_pos = d_pos = 0
    out = []
    for i in range(n):
        choice = rng.choice(3, p=weights[i])
        if choice == 0 and o_pos < o_idx.size:
            out.append(float(origin_events[o_idx[o_pos]]))
            o_pos += 1
        elif choice == 1 and m_pos < m_idx.size:
            out.append(float(middle_events[m_idx[m_pos]]))
            m_pos += 1
        elif choice == 2 and d_pos < d_idx.size:
            out.append(float(destination_events[d_idx[d_pos]]))
            d_pos += 1
        else:
            # fall back if exhausted
            if o_pos < o_idx.size:
                out.append(float(origin_events[o_idx[o_pos]]))
                o_pos += 1
    out = np.sort(np.asarray(out, dtype=np.float64))
    sp = np.diff(out)
    sp = sp[sp > 0]
    if sp.size and sp.mean() > 0:
        out = np.cumsum(np.concatenate([[0.0], sp / sp.mean()]))
    return out


# ─── Top-level blended-transition generator ────────────────────────────────


CLASS_PAIRS = [
    ('GUE',     'Poisson'),
    ('Poisson', 'GUE'),
    ('GUE',     'TL'),
    ('TL',      'GUE'),
    ('Poisson', 'TL'),
    ('TL',      'Poisson'),
    ('GUE',     'mixed'),
    ('mixed',   'GUE'),
]


def gen_blended_transition(
        origin: str,
        destination: str,
        shape: str,
        n_points: int = 10_000,
        seed: int = 0,
        shape_kwargs: Optional[dict] = None,
        middle_class: Optional[str] = None,
        ) -> np.ndarray:
    """Generate a single blended-transition calibrator.

    `origin`, `destination`: keys in CLASS_GENERATORS.
    `shape`: key in SHAPES_TWO_STATE or SHAPES_THREE_STATE.
    `n_points`: total event count (≥ 10⁴ for stable per-window
        classification).
    `seed`: global RNG seed; origin/middle/destination classes use
        derived seeds for independence.
    `shape_kwargs`: passed to the shape function.
    `middle_class`: required for metastable_middle; defaults to
        'mixed' if not specified.

    Returns sorted unit-mean event sequence of length ~n_points.
    """
    if origin not in CLASS_GENERATORS:
        raise ValueError(f"unknown origin class: {origin}")
    if destination not in CLASS_GENERATORS:
        raise ValueError(f"unknown destination class: {destination}")
    rng = np.random.default_rng(seed)
    shape_kwargs = shape_kwargs or {}

    o = CLASS_GENERATORS[origin](n_points, seed=seed * 3 + 1)
    d = CLASS_GENERATORS[destination](n_points, seed=seed * 3 + 2)

    if shape in SHAPES_TWO_STATE:
        w = SHAPES_TWO_STATE[shape](n_points, **shape_kwargs)
        return _blend_two_class(o, d, w, rng)
    elif shape in SHAPES_THREE_STATE:
        if middle_class is None:
            middle_class = 'mixed' if 'mixed' not in (origin, destination) \
                            else 'TL'
        m = CLASS_GENERATORS[middle_class](n_points, seed=seed * 3 + 3)
        w = SHAPES_THREE_STATE[shape](n_points, **shape_kwargs)
        return _blend_three_class(o, m, d, w, rng)
    else:
        raise ValueError(f"unknown shape: {shape}")


def gen_stationary_control(class_name: str,
                            n_points: int = 10_000,
                            seed: int = 0) -> np.ndarray:
    """Generate a stationary (no-transition) calibrator for the
    diagnostic's false-positive control."""
    if class_name not in CLASS_GENERATORS:
        raise ValueError(f"unknown class: {class_name}")
    out = CLASS_GENERATORS[class_name](n_points, seed=seed)
    sp = np.diff(out)
    sp = sp[sp > 0]
    if sp.size and sp.mean() > 0:
        out = np.cumsum(np.concatenate([[0.0], sp / sp.mean()]))
    return out


def enumerate_blended_panel(seeds: tuple = (0,)) -> list[dict]:
    """Return the full panel of blended calibrator specifications.

    Each entry:
      name, origin, destination, shape, shape_kwargs, seed
    """
    panel = []
    for o, d in CLASS_PAIRS:
        for shape in SHAPES_TWO_STATE:
            for seed in seeds:
                panel.append(dict(
                    name=f"blend_{o}_to_{d}_{shape}_s{seed}",
                    kind='blended_two_state',
                    origin=o, destination=d,
                    shape=shape, shape_kwargs={}, seed=seed))
        for shape in SHAPES_THREE_STATE:
            for seed in seeds:
                panel.append(dict(
                    name=f"blend_{o}_to_{d}_{shape}_s{seed}",
                    kind='blended_three_state',
                    origin=o, destination=d,
                    shape=shape, shape_kwargs={}, seed=seed,
                    middle_class=None))
    # Stationary controls
    for cls in CLASS_GENERATORS:
        if cls == 'periodic':
            continue   # alias for TL
        for seed in seeds:
            panel.append(dict(
                name=f"stationary_{cls}_s{seed}",
                kind='stationary',
                class_name=cls, seed=seed))
    return panel


__all__ = [
    'gen_poisson', 'gen_wigner_gue', 'gen_periodic', 'gen_mixed',
    'CLASS_GENERATORS',
    'shape_sharp_step', 'shape_linear_ramp', 'shape_sigmoidal',
    'shape_exponential_approach', 'shape_damped_oscillatory',
    'shape_metastable_middle',
    'SHAPES_TWO_STATE', 'SHAPES_THREE_STATE',
    'gen_blended_transition', 'gen_stationary_control',
    'CLASS_PAIRS', 'enumerate_blended_panel',
]
