"""
phase34a/run_falsify.py — Sub-question 4: multi-order falsification on
the RF spikes flagged in sub-question 3.

The Mertens function M(n) changes value only when μ(n) ≠ 0, i.e., at
squarefree integers.  Therefore every Mertens sign-change position is
a squarefree integer.  The squarefree integers themselves have a
fixed, non-uniform residue-class density profile (e.g., zero density
at residue 0 mod 4 because 4|n implies non-squarefree; odd:even ≈ 2:1
overall).  This residue-class profile *automatically* produces non-
zero RF amplitudes at q = 2, 3, 4 etc., without any "hidden
arithmetic structure" beyond the squarefree-filter restriction.

The rate-matched Poisson null in sub-question 3 destroys the
squarefree filter, so any RF spike survives that null almost
trivially.  This is the wrong null for the question "does the Mertens
sign-change sequence carry integer-period structure *beyond* the
squarefree-density profile?".

This module runs three falsifications:

  (A) Squarefree-restricted local-density Poisson surrogate.
      Per density bin, sample integer events uniformly from the
      squarefree integers in that bin.  The right null for "novel
      arithmetic structure beyond the squarefree filter".  If the
      real |a_q| spike persists relative to this null → genuine
      structure beyond the filter; otherwise → filter-density
      artefact.

  (B) Within-window stability of |a_q| at flagged q across 5
      non-overlapping windows.  A genuine signal should appear in
      every window, not be confined to one.

  (C) Cross-check on a second tabulation.  We do not have access to
      an independent published table (Hurst 1995 / Kuznetsov 2011);
      the existing project tabulation in
      data/mertens_liouville_results.json was generated by an
      earlier independent sieve run, and reports identical event-
      count (3866) and M(decade) values.  We compare our
      sign-change positions against that earlier result for self-
      consistency.

Output: data/phase34a_results/falsify.json
"""
from __future__ import annotations

import json
import os
import sys
import time
from collections import Counter
from pathlib import Path

import numpy as np

THIS_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(THIS_DIR)
sys.path.insert(0, ROOT_DIR)
sys.path.insert(0, THIS_DIR)

from mertens_events import load_or_compute, mu_sieve
from fast_rf import fast_rf_indicator, fast_padic_v4

OUT_DIR = Path(ROOT_DIR) / 'data' / 'phase34a_results'
OUT_DIR.mkdir(parents=True, exist_ok=True)

Q_MAX = 30
RF_SPIKE_FACTOR = 5.0
PRIMES = (2, 3, 5, 7, 11, 13)
N_SEEDS = 1000
K_BINS = 50
N_WINDOWS = 5


def squarefree_mask(N: int) -> np.ndarray:
    """Boolean array of length N+1 where mask[n] is True iff n is squarefree."""
    mu = mu_sieve(N)
    return mu != 0


def squarefree_indices(N: int) -> np.ndarray:
    """Sorted int64 array of squarefree integers in [1, N]."""
    m = squarefree_mask(N)
    idx = np.where(m)[0].astype(np.int64)
    return idx[idx > 0]


# ─── (A) squarefree-restricted local-density Poisson surrogate ───────────────

def squarefree_local_density(positions: np.ndarray, sqf: np.ndarray,
                              seed: int, K: int = K_BINS,
                              t_min: int | None = None,
                              t_max: int | None = None) -> np.ndarray:
    """Sample a Poisson surrogate with per-bin event counts ≈ real, but
    drawing each event uniformly from the squarefree integers in that
    bin (preserves the squarefree-filter residue-class density).

    sqf  — sorted array of all squarefree integers in [t_min, t_max].
    """
    pos = np.asarray(positions, dtype=np.int64)
    if pos.size == 0 or sqf.size == 0:
        return pos.copy()
    rng = np.random.default_rng(seed)
    lo = int(pos.min()) if t_min is None else int(t_min)
    hi = int(pos.max()) if t_max is None else int(t_max)
    edges = np.linspace(lo, hi + 1, K + 1).astype(np.int64)
    edges[-1] = hi + 1
    counts, _ = np.histogram(pos, bins=edges)

    # For each bin, identify squarefree integers in [edges[i], edges[i+1]).
    # Use searchsorted on sqf to slice.
    out_chunks = []
    sqf_l = np.searchsorted(sqf, edges[:-1])
    sqf_r = np.searchsorted(sqf, edges[1:])
    for i in range(K):
        bin_sqf = sqf[sqf_l[i]:sqf_r[i]]
        if bin_sqf.size == 0:
            continue
        k_pois = int(rng.poisson(counts[i]))
        if k_pois == 0:
            continue
        if k_pois > bin_sqf.size:
            k_pois = bin_sqf.size
        # without replacement
        picks = rng.choice(bin_sqf.size, size=k_pois, replace=False)
        out_chunks.append(bin_sqf[picks])
    if not out_chunks:
        return np.zeros(0, dtype=np.int64)
    out = np.concatenate(out_chunks).astype(np.int64)
    out.sort()
    return out


def falsification_A(positions: np.ndarray,
                     label: str,
                     n_bins: int,
                     sqf: np.ndarray,
                     spike_qs: list[int]) -> dict:
    print(f"\n  ── (A) squarefree-restricted surrogate [{label}] ──")
    real_amps = fast_rf_indicator(positions, q_max=Q_MAX,
                                    n_bins=n_bins)['amplitudes']
    pmin = int(positions.min())
    pmax = int(positions.max())
    sur_amps = np.zeros((N_SEEDS, Q_MAX), dtype=np.float64)
    sur_dom_per_q = np.zeros(N_SEEDS, dtype=np.int32)
    t0 = time.perf_counter()
    for s in range(N_SEEDS):
        sp = squarefree_local_density(positions, sqf, seed=s,
                                        K=K_BINS, t_min=pmin, t_max=pmax)
        if sp.size < 10:
            continue
        rf = fast_rf_indicator(sp, q_max=Q_MAX, n_bins=n_bins)
        sur_amps[s] = rf['amplitudes']
        pv4 = fast_padic_v4(sp, primes=PRIMES, q_max=Q_MAX, n_bins=n_bins)
        sur_dom_per_q[s] = pv4.get('dominant_prime_per_q', 0)
    print(f"    {N_SEEDS} squarefree-restricted surrogates in "
          f"{time.perf_counter() - t0:.1f}s")

    rf_real_vs_sqf = []
    for q in spike_qs:
        sa = sur_amps[:, q - 1]
        p_val = float(np.mean(sa >= real_amps[q - 1]))
        ratio = float(real_amps[q - 1] / max(sa.mean(), 1e-30))
        survives = p_val < 0.001
        rf_real_vs_sqf.append(dict(
            q=int(q),
            real_amp=float(real_amps[q - 1]),
            sqf_sur_mean=float(sa.mean()),
            sqf_sur_std=float(sa.std()),
            ratio_real_to_sur_mean=ratio,
            p_value_vs_sqf=p_val,
            survives_sqf_null_p_lt_0p001=bool(survives),
        ))
        print(f"    q={q:>2}  real |a_q|={real_amps[q - 1]:.4e}  "
              f"sqf-sur mean={sa.mean():.4e}  ratio={ratio:6.2f}×  "
              f"p={p_val:.4f}  survives={survives}")

    sur_dom_counter = Counter(sur_dom_per_q.tolist())
    print(f"    p-adic v4 dominant_prime_per_q surrogate distribution "
          f"(squarefree-restricted): {dict(sorted(sur_dom_counter.items()))}")
    return dict(
        spike_q_vs_squarefree_null=rf_real_vs_sqf,
        squarefree_sur_dom_per_q_distribution=dict(sur_dom_counter),
        squarefree_sur_amps_mean_per_q=sur_amps.mean(axis=0).tolist(),
        squarefree_sur_amps_std_per_q=sur_amps.std(axis=0).tolist(),
    )


# ─── (B) within-window stability ─────────────────────────────────────────────

def falsification_B(positions: np.ndarray, label: str,
                     pmin: int, pmax: int,
                     spike_qs: list[int]) -> dict:
    print(f"\n  ── (B) within-window stability ({N_WINDOWS} windows) "
          f"[{label}] ──")
    edges = np.linspace(pmin, pmax + 1, N_WINDOWS + 1).astype(np.int64)
    per_window = []
    for w in range(N_WINDOWS):
        w_lo = int(edges[w])
        w_hi = int(edges[w + 1])
        sub = positions[(positions >= w_lo) & (positions < w_hi)]
        if sub.size < 30:
            per_window.append(dict(window=w, w_lo=w_lo, w_hi=w_hi,
                                     n_events=int(sub.size),
                                     amps_at_spike_qs=None,
                                     note='underpowered'))
            print(f"    win {w}: [{w_lo:>8}, {w_hi:>8}) "
                  f"n={sub.size} UNDERPOWERED")
            continue
        rf = fast_rf_indicator(sub, q_max=Q_MAX, n_bins=w_hi - w_lo)
        amps_at_q = {int(q): float(rf['amplitudes'][q - 1])
                     for q in spike_qs}
        per_window.append(dict(window=w, w_lo=w_lo, w_hi=w_hi,
                                 n_events=int(sub.size),
                                 amps_at_spike_qs=amps_at_q))
        cells = "  ".join(f"q={q}:{amps_at_q[q]:.2e}" for q in spike_qs)
        print(f"    win {w}: [{w_lo:>8}, {w_hi:>8}) n={sub.size:>5}  {cells}")
    # Stability metric: coefficient of variation across well-powered
    # windows of |a_q| at each spike q.
    stability = {}
    for q in spike_qs:
        vals = [w['amps_at_spike_qs'][q] for w in per_window
                if w.get('amps_at_spike_qs') is not None]
        if len(vals) >= 3:
            arr = np.asarray(vals)
            cv = float(arr.std() / max(abs(arr.mean()), 1e-30))
            stability[int(q)] = dict(mean=float(arr.mean()),
                                       std=float(arr.std()),
                                       cv=cv,
                                       n_wells=len(vals))
            print(f"    q={q:>2}  across {len(vals)} wells: mean={arr.mean():.3e}, "
                  f"std={arr.std():.3e}, CV={cv:.3f}")
    return dict(per_window=per_window, stability=stability)


# ─── (C) cross-check vs stored project tabulation ───────────────────────────

def falsification_C(sc: np.ndarray) -> dict:
    print(f"\n  ── (C) cross-check vs project's earlier sieve "
          f"(data/mertens_liouville_results.json) ──")
    prior = ROOT_DIR + '/data/mertens_liouville_results.json'
    try:
        with open(prior) as f:
            d = json.load(f)
        prior_n_sc = int(d['mertens']['n_sign_changes'])
        prior_decades = d['mertens']['M_at_decades']
    except Exception as e:
        print(f"    no prior tabulation: {e}")
        return dict(prior_available=False)
    new = load_or_compute(10**7)
    cur_n_sc = int(new['signchanges'].size)
    cur_decades = new['M_at_decades']
    match_n = (prior_n_sc == cur_n_sc)
    match_decades = (prior_decades == cur_decades)
    print(f"    prior n_sign_changes: {prior_n_sc}   current: {cur_n_sc}   "
          f"match: {match_n}")
    print(f"    prior M(decades): {prior_decades}")
    print(f"    current M(decades): {cur_decades}   match: {match_decades}")
    return dict(prior_available=True,
                 prior_n_sign_changes=prior_n_sc,
                 current_n_sign_changes=cur_n_sc,
                 prior_M_at_decades=prior_decades,
                 current_M_at_decades=cur_decades,
                 n_sign_changes_match=bool(match_n),
                 M_decades_match=bool(match_decades))


# ─── orchestrator ────────────────────────────────────────────────────────────

def main(N_MAX: int = 10**7) -> dict:
    print("=" * 72)
    print("Phase 34a Sub-question 4: multi-order falsification on RF spikes")
    print("=" * 72)
    print(f"  N_SEEDS={N_SEEDS}, K_BINS={K_BINS}, N_WINDOWS={N_WINDOWS}")

    d = load_or_compute(N_MAX)
    sc = d['signchanges']

    # Load prior sub-question 3 result to get spike_qs that survived Poisson null
    sur_path = OUT_DIR / 'rf_padic_survey.json'
    with open(sur_path) as f:
        survey = json.load(f)
    spike_qs_full = [r['q'] for r in survey['full']['rf_survivors']
                     if r['survives_p_lt_0p001']]
    spike_qs_dense = [r['q'] for r in survey['dense_1_to_4e6']['rf_survivors']
                      if r['survives_p_lt_0p001']]
    print(f"  Sub-3 Poisson-surviving spike q (dense): {spike_qs_dense}")
    print(f"  Sub-3 Poisson-surviving spike q (full):  {spike_qs_full}")

    # Squarefree mask up to N_MAX
    print(f"\n  computing squarefree integers in [1, {N_MAX}]…")
    t0 = time.perf_counter()
    sqf = squarefree_indices(N_MAX)
    print(f"    {sqf.size} squarefree integers ({100 * sqf.size / N_MAX:.1f}% "
          f"of [1, N]) in {time.perf_counter() - t0:.1f}s")

    out_obj: dict = {
        'N_MAX': int(N_MAX),
        'Q_MAX': Q_MAX,
        'N_SEEDS': N_SEEDS,
        'K_BINS': K_BINS,
        'N_WINDOWS': N_WINDOWS,
        'spike_qs_from_sub3': dict(dense=spike_qs_dense, full=spike_qs_full),
        'n_squarefree_in_N': int(sqf.size),
        'fraction_squarefree': float(sqf.size / N_MAX),
    }

    # ── dense window ──
    dense = sc[sc < 4 * 10**6]
    dense_sqf = sqf[sqf < 4 * 10**6]
    print(f"\n=== Dense window [1, 4e6], n_events={dense.size}, "
          f"squarefrees={dense_sqf.size} ===")
    out_obj['dense_1_to_4e6'] = {
        'A_squarefree_restricted': falsification_A(dense, 'dense [1, 4e6]',
                                                     n_bins=4 * 10**6,
                                                     sqf=dense_sqf,
                                                     spike_qs=spike_qs_dense),
        'B_within_window_stability': falsification_B(dense, 'dense [1, 4e6]',
                                                       pmin=1,
                                                       pmax=4 * 10**6 - 1,
                                                       spike_qs=spike_qs_dense),
    }

    # ── full sequence ──
    print(f"\n=== Full sequence [1, 1e7], n_events={sc.size}, "
          f"squarefrees={sqf.size} ===")
    out_obj['full'] = {
        'A_squarefree_restricted': falsification_A(sc, 'full [1, 1e7]',
                                                     n_bins=N_MAX,
                                                     sqf=sqf,
                                                     spike_qs=spike_qs_full),
        'B_within_window_stability': falsification_B(sc, 'full [1, 1e7]',
                                                       pmin=1,
                                                       pmax=N_MAX,
                                                       spike_qs=spike_qs_full),
    }

    out_obj['C_cross_tabulation'] = falsification_C(sc)

    out_path = OUT_DIR / 'falsify.json'
    with open(out_path, 'w') as f:
        json.dump(out_obj, f, indent=2, default=str)
    print(f"\n  → {out_path}")
    return out_obj


if __name__ == '__main__':
    main()
